# Generated by Django 4.2.7 on 2023-11-22 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_bookclub_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
